esphome:
  name: esphome-web-33233c
  friendly_name: TCL Aircon
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev


# Enable logging
logger:


# Enable Home Assistant API
api:
  encryption:
    key: "YUhklU6NgLzZsdfdsfsdfsdfsdf"

#Wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none


# Allow Over-The-Air updates
ota:
- platform: esphome

# Enable web server
web_server:
  port: 80

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: IP

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

substitutions:
  device_name: esphome_web_33233c
  humanly_name: TCL Aircon
  uart_rx: GPIO1
  uart_tx: GPIO3
  receive_led: GPIO2
  transmit_led: GPIO2

packages:
  remote_package:
    url: https://github.com/s3n3rgy/TCL_AC.git
    ref: master
    files:
      - packages/core.yaml  
 #     - packages/leds.yaml 
    refresh: 30s
